-- Create database
CREATE DATABASE IF NOT EXISTS FRAUD_DB;

USE DATABASE FRAUD_DB;

CREATE SCHEMA IF NOT EXISTS RAW; 

-- raw CSV data goes here

CREATE SCHEMA IF NOT EXISTS STAGING; 

-- cleaned or joined 
CREATE SCHEMA IF NOT EXISTS FEATURES; 

-- ML feature tables

CREATE SCHEMA IF NOT EXISTS ML; 

-- model predictions

-- Set session defaults
USE WAREHOUSE FRAUD_WH;
USE DATABASE FRAUD_DB;
USE SCHEMA RAW;

SHOW SCHEMAS IN DATABASE FRAUD_DB;

-- Create empty RAW_TRANSACTION table
CREATE OR REPLACE TABLE FRAUD_DB.RAW.RAW_TRANSACTION (ID VARCHAR);

-- Create empty RAW_IDENTITY table
CREATE OR REPLACE TABLE FRAUD_DB.RAW.RAW_IDENTITY (ID VARCHAR);